"""
F1+F2 — OpenFOAM 케이스 디렉터리 생성 (blockMesh 배경격자 + snappyHexMesh)

1차 스코프: tutorial 급 형상만.
  · 벤드 없음 + 덕트 밀폐(sealed) + 관이 덕트 z 범위와 일치
  → 배경격자 = air_bbox, blockMesh 6면에 patch 이름을 직접 부여
    (Fluent 의 케이싱이 하던 일을 blockMesh 가 공짜로 해줌)
probe(벤드가 덕트 밖으로 나감)는 배경을 global_bbox 로 잡고 공기 외곽을
snappy 가 만들게 해야 하므로 별도 단계에서 확장함.

관벽 처리: Phase 2 는 A-lite — solid_tube 를 cellZone 으로 실제 메시.
  snappy 에는 Fluent 의 thin-volume 이 없어 관벽(t=0.65mm)에 셀을 넣으려면
  표면 level 을 t 미만 크기까지 올려야 함. 셀 증가를 감수하고 위상 검증을
  우선함. B안(baffle+thermalBaffle, 관벽 제거)은 Phase 3 에서 결정.

사이징: meshing.sizing() 의 값만 사용. 사람이 만질 값 없음.
  배경 h_bg = 2·h_air (Fluent 상·하류와 동일)
  level 1 = h_air (코어), level L_ref ≈ h_ref, level L_wall < t_wall
"""
from __future__ import annotations

import math
import shutil
from pathlib import Path

from .params import FTHXParams
from . import meshing as MSH
from .foam_stl import export_stl


def _scale_stl(src: Path, dst: Path, f: float = 0.001) -> None:
    """binary STL 좌표 스케일 (mm→m). blockMesh 는 convertToMeters 로
    변환되지만 triSurface·eMesh·locationInMesh 는 변환되지 않으므로
    케이스에 들어가는 STL 은 m 단위여야 함 (실측: locationInMesh 단위
    불일치로 FATAL — 'Point ... is not inside the mesh')."""
    import numpy as np
    b = bytearray(src.read_bytes())
    n = int.from_bytes(b[80:84], "little")
    arr = np.frombuffer(b, dtype="<f4", count=n * 12 + 0, offset=84).copy() if False else None
    # 레코드 50B = 법선3f + 정점9f + attr2B → f4 view 는 불가(50 이 4의 배수 아님)
    import struct
    for i in range(n):
        off = 84 + i * 50
        vals = struct.unpack_from("<12f", b, off)
        struct.pack_into("<12f", b, off, *(v * f for v in vals))
    dst.write_bytes(bytes(b))

FOAM_HEADER = """\
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      {obj};
}}
// generated by fthx.openfoam — 수정하지 말 것 (params 에서 재생성됨)
"""


def _hdr(obj: str) -> str:
    return FOAM_HEADER.format(obj=obj)


def _level_for(h_bg: float, target: float, slack: float = 1.0) -> int:
    """배경 h_bg 에서 target·slack 이하가 되는 최소 refinement level.
    slack>1 이면 목표보다 약간 굵은 level 을 허용 (한 단계 아래로 과세분 방지)."""
    lv = 0
    h = h_bg
    while h > target * slack * (1 + 1e-9):
        lv += 1
        h /= 2.0
    return lv


def plan(p: FTHXParams) -> dict:
    """사이징 → snappy level 계획. 게이트/검산에 쓰는 수치를 한곳에 모음."""
    s = MSH.sizing(p)
    t = p.tube
    h_bg = 2.0 * s["h_air_mm"]
    t_wall = (t.Do - t.Di) / 2.0
    lv_core = _level_for(h_bg, s["h_air_mm"])                 # 보통 1
    lv_ref = _level_for(h_bg, s["h_ref_mm"], slack=1.2)       # 보통 2 (0.794≈h_ref)
    lv_wall = _level_for(h_bg, 0.75 * t_wall)                 # 벽에 셀이 들어가는 크기
    return {"sizing": s, "h_bg_mm": h_bg, "t_wall_mm": t_wall,
            "lv_core": lv_core, "lv_ref": lv_ref, "lv_wall": lv_wall,
            "h_at": {f"level{l}": h_bg / 2 ** l
                     for l in range(max(lv_wall, lv_ref) + 1)}}


def _block_mesh_dict(p: FTHXParams, pl: dict) -> str:
    d, dk = p.domain, p.duct_box
    x0, x1 = p.core_bbox[0], p.core_bbox[1]
    xa, xb = x0 - d.L_up, x1 + d.L_down
    ya, yb, za, zb = dk["y0"], dk["y1"], dk["z0"], dk["z1"]
    h = pl["h_bg_mm"]
    n = [max(1, round((b - a) / h)) for a, b in ((xa, xb), (ya, yb), (za, zb))]
    v = [(xa, ya, za), (xb, ya, za), (xb, yb, za), (xa, yb, za),
         (xa, ya, zb), (xb, ya, zb), (xb, yb, zb), (xa, yb, zb)]
    verts = "\n".join(f"    ({a} {b} {c})" for a, b, c in v)
    return _hdr("blockMeshDict") + f"""
convertToMeters 0.001;      // 형상 단위 = mm

vertices
(
{verts}
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({n[0]} {n[1]} {n[2]}) simpleGrading (1 1 1)
);

boundary
(
    air_inlet  {{ type patch; faces ((0 4 7 3)); }}
    air_outlet {{ type patch; faces ((1 2 6 5)); }}
    duct_wall  {{ type wall;  faces ((0 1 5 4) (3 7 6 2)
                                     (0 3 2 1) (4 5 6 7)); }}
);
"""


def _feature_dict(stl_names: list[str]) -> str:
    body = ""
    for n in stl_names:
        body += f"""
{n}.stl
{{
    extractionMethod    extractFromSurface;
    includedAngle       150;
    writeObj            no;
}}
"""
    return _hdr("surfaceFeatureExtractDict") + body


def _snappy_dict(p: FTHXParams, pl: dict, zones: dict[str, int]) -> str:
    d, dk = p.domain, p.duct_box
    x0 = p.core_bbox[0]
    # 공기 내부 점 = 상류 박스 중심 (셀 면과 겹치지 않게 미세 오프셋)
    loc = tuple(v / 1000.0 for v in (         # [m] — STL·메시와 단위 일치
        (x0 - d.L_up + x0) / 2 + 0.0123,
        (dk["y0"] + dk["y1"]) / 2 + 0.0231,
        (dk["z0"] + dk["z1"]) / 2 + 0.0312))
    geom, feat, surf = "", "", ""
    for name, lv in zones.items():
        geom += f'    {name}.stl {{ type triSurfaceMesh; name {name}; }}\n'
        feat += f'    {{ file "{name}.eMesh"; level {lv}; }}\n'
        surf += (f"        {name}\n        {{\n"
                 f"            level ({lv} {lv});\n"
                 f"            faceZone {name};\n"
                 f"            cellZone {name};\n"
                 f"            cellZoneInside inside;\n        }}\n")
    core = next(n for n in zones if n.startswith("fluid_air_core"))
    return _hdr("snappyHexMeshDict") + f"""
castellatedMesh true;
snap            true;
addLayers       false;      // y+ 벽함수 범위 실측(190/131) — 프리즘 불필요

geometry
{{
{geom}}}

castellatedMeshControls
{{
    maxLocalCells       2000000;
    maxGlobalCells      8000000;
    minRefinementCells  0;
    nCellsBetweenLevels 2;
    resolveFeatureAngle 30;

    features
    (
{feat}    );

    refinementSurfaces
    {{
{surf}    }}

    refinementRegions
    {{
        {core} {{ mode inside; levels ((1e15 {pl['lv_core']})); }}
    }}

    locationInMesh ({loc[0]} {loc[1]} {loc[2]});   // 상류 공기 내부 [m]
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch            3;
    tolerance               2.0;
    nSolveIter              50;
    nRelaxIter              5;
    nFeatureSnapIter        10;
    implicitFeatureSnap     false;
    explicitFeatureSnap     true;
    multiRegionFeatureSnap  true;   // cellZone 계면에서도 feature 스냅
}}

addLayersControls
{{
    relativeSizes true;
    layers {{ }}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.25;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 5;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}

meshQualityControls
{{
    #includeEtc "caseDicts/meshQualityDict"
    minTetQuality   1e-15;
    nSmoothScale    4;
    errorReduction  0.75;
}}

writeFlags ();
mergeTolerance 1e-6;
"""


_MINI = {
    "controlDict": """
application     snappyHexMesh;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         1;
deltaT          1;
writeControl    timeStep;
writeInterval   1;
""",
    "fvSchemes": """
ddtSchemes {}
gradSchemes {}
divSchemes {}
laplacianSchemes {}
interpolationSchemes {}
snGradSchemes {}
""",
    "fvSolution": """
solvers {}
""",
}

_ALLRUN = """\
#!/usr/bin/env bash
# 메시 생성 + 진단 (한 번 실행으로 여러 검산을 같이 수행)
cd "$(dirname "$0")"
# OpenFOAM 환경 자동 탐지 (미리 source 안 해도 동작)
if ! command -v blockMesh >/dev/null 2>&1; then
    for rc in /usr/lib/openfoam/openfoam*/etc/bashrc; do
        [ -f "$rc" ] && source "$rc" && break
    done
fi
command -v blockMesh >/dev/null 2>&1 || { echo "OpenFOAM 을 찾을 수 없음"; exit 2; }
set -e
run() { echo ">>> $1"; "$@" > "log.$1" 2>&1 || { echo "<<< $1 실패 — log.$1"; exit 1; }; echo "<<< $1 OK"; }

run surfaceFeatureExtract
run blockMesh
run snappyHexMesh -overwrite
run checkMesh -constant

echo "──────── 요약 ────────"
grep -E "^Snapped mesh" log.snappyHexMesh | tail -1 || true
echo "── cellZones (이름: 셀 수) — 0 이 있으면 존 형성 실패"
awk '/^\(?[A-Za-z_]/{z=$1; sub(/^\(/,"",z)} /List<label>/{getline n; print "  " z ": " n}' constant/polyMesh/cellZones
grep -E "Mesh OK|Failed .* mesh checks" log.checkMesh
"""


def write_case(p: FTHXParams, case_dir: str, force: bool = False) -> dict:
    """tutorial 급 형상의 snappy 케이스 생성. 반환: plan + 파일 목록."""
    d = p.domain
    if d.include_bends:
        raise NotImplementedError(
            "벤드 포함 형상(probe)은 배경격자를 global_bbox 로 잡는 확장이 "
            "필요함 — Phase 5. 지금은 tutorial 급만 지원.")
    if not p.duct.sealed:
        raise NotImplementedError("덕트 간극(바이패스) 형상은 미지원 — Phase 5.")

    case = Path(case_dir)
    if case.exists() and force:
        shutil.rmtree(case)
    (case / "system").mkdir(parents=True, exist_ok=True)
    (case / "constant" / "triSurface").mkdir(parents=True, exist_ok=True)
    (case / "0").mkdir(exist_ok=True)

    # STL 은 여기서 직접 생성 (F0 내장 검증 포함) → triSurface 로 복사
    meta = export_stl(p, outdir=str(case / "_stl_tmp"))
    stl_names = []
    for b in meta["bodies"].values():
        src = case / "_stl_tmp" / b["file"]
        _scale_stl(src, case / "constant" / "triSurface" / b["file"])
        stl_names.append(b["file"][:-4])
    shutil.rmtree(case / "_stl_tmp")

    pl = plan(p)
    zones = {}
    for n in sorted(stl_names):
        if n.startswith("fluid_air_core"):
            zones[n] = pl["lv_core"]
        elif n.startswith("solid_tube"):
            zones[n] = pl["lv_wall"]
        elif n.startswith("fluid_ref"):
            zones[n] = pl["lv_ref"]
        elif n.startswith("fluid_air_"):
            continue          # 상·하류는 배경 그대로 = 별도 존 불필요 (공기 연속체)
        else:
            zones[n] = pl["lv_ref"]

    (case / "system" / "blockMeshDict").write_text(
        _block_mesh_dict(p, pl), encoding="utf-8")
    (case / "system" / "snappyHexMeshDict").write_text(
        _snappy_dict(p, pl, zones), encoding="utf-8")
    (case / "system" / "surfaceFeatureExtractDict").write_text(
        _feature_dict(sorted(zones)), encoding="utf-8")
    for name, body in _MINI.items():
        (case / "system" / name).write_text(_hdr(name) + body, encoding="utf-8")
    ar = case / "Allrun.mesh"
    ar.write_text(_ALLRUN, encoding="utf-8")
    ar.chmod(0o755)

    # 상·하류 STL 은 triSurface 에서 제거 — 존으로 안 쓰므로 혼동 방지
    for n in stl_names:
        if n.startswith("fluid_air_up") or n.startswith("fluid_air_down"):
            (case / "constant" / "triSurface" / f"{n}.stl").unlink()

    pl["zones"] = zones
    pl["case_dir"] = str(case)
    pl["gate"] = {
        "fluent_ref_cells": 68641,
        "rule": "셀 수가 Fluent tutorial 과 같은 자릿수(<10배)면 통과. "
                "관벽 level 상향(A-lite)으로 증가는 예상된 것",
    }
    return pl
